# Generated by Django 5.0.6 on 2024-07-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0002_remove_customuser_profile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
    ]
