# Generated by Django 5.0.6 on 2024-07-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0003_remove_profile_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('ZH', 'Chinese')], max_length=100),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('1', '1st Grade'), ('2', '2nd Grade'), ('12', '12th Grade'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('subjects_of_interest', models.TextField(blank=True, help_text="List subjects you're interested in, separated by commas")),
                ('learning_goals', models.TextField(blank=True, help_text='Describe your learning goals')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hira.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifications', models.TextField(blank=True, help_text='List your certifications, separated by commas')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('education', models.TextField(blank=True, help_text='Your educational background')),
                ('teaching_style', models.TextField(blank=True, help_text='Describe your teaching approach')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hira.profile')),
            ],
        ),
    ]
