# Generated by Django 5.0.6 on 2024-07-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_code',
        ),
    ]
