# Generated by Django 5.0.6 on 2024-07-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0007_remove_customuser_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, help_text='List your certifications, separated by commas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, help_text='Your educational background'),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', '1st Grade'), ('2', '2nd Grade'), ('12', '12th Grade'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_goals',
            field=models.TextField(blank=True, help_text='Describe your learning goals'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects_of_interest',
            field=models.TextField(blank=True, help_text="List subjects you're interested in, separated by commas"),
        ),
        migrations.AddField(
            model_name='profile',
            name='teaching_style',
            field=models.TextField(blank=True, help_text='Describe your teaching approach'),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
