# Generated by Django 5.0.6 on 2024-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0009_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
