# Generated by Django 5.0.6 on 2024-07-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0010_profile_google_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='google_credentials',
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
