# Generated by Django 5.0.6 on 2024-07-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0014_classschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='teacher',
        ),
    ]
