# Generated by Django 5.0.6 on 2024-07-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0015_remove_classschedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules_as_teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
