# Generated by Django 5.0.6 on 2024-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0020_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
