# Generated by Django 5.0.6 on 2024-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0021_classschedule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
